/* Generated By:JavaCC: Do not edit this line. AssignmentConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 1;
  /** RegularExpression Id. */
  int DEF = 2;
  /** RegularExpression Id. */
  int MAIN = 3;
  /** RegularExpression Id. */
  int FUNC_NAME = 4;
  /** RegularExpression Id. */
  int PARAMETER = 5;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int TIMES = 8;
  /** RegularExpression Id. */
  int STRING = 9;
  /** RegularExpression Id. */
  int DECIMAL = 10;
  /** RegularExpression Id. */
  int LBRACE = 11;
  /** RegularExpression Id. */
  int RBRACE = 12;
  /** RegularExpression Id. */
  int SPACE = 13;
  /** RegularExpression Id. */
  int LEFT_PARENTHESIS = 14;
  /** RegularExpression Id. */
  int RIGHT_PARENTHESIS = 15;
  /** RegularExpression Id. */
  int SEMICOLON = 16;
  /** RegularExpression Id. */
  int SPECIAL = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<EOL>",
    "\"DEF\"",
    "\"MAIN\"",
    "<FUNC_NAME>",
    "<PARAMETER>",
    "<NUMBER>",
    "\"+\"",
    "\"*\"",
    "<STRING>",
    "<DECIMAL>",
    "\"{\"",
    "\"}\"",
    "\" \"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "<SPECIAL>",
  };

}
