/* Assignment.java */
/* Generated By:JavaCC: Do not edit this line. Assignment.java */
import java.util.*;

public class Assignment implements AssignmentConstants {

    ArrayList<String> definedFuncs = new ArrayList<String>();
    HashMap<String, Integer> calledFuncs = new HashMap<String, Integer>();

    // Hashmap will store the function names alongside sections of the function bodies
    // The arraylist in the map will store each token separately
    HashMap<String, ArrayList<String>> functions = new HashMap<String, ArrayList<String>>();

    // stores all the functions called in the currentFunc
    ArrayList<String> callsInCurrent = new ArrayList<String>();

    // keeps track of the function that is being parsed
    String currentFunc = "";
    int lineNumber = 1;
    boolean isMain = false;
    boolean inCall = false;
    boolean divergence = false;

    public static void main(String args []) throws ParseException, TokenMgrError {

        Assignment parser = new Assignment(System.in);
        try {
            parser.Start();
        } catch (ParseException e) {
            System.out.println("FAIL");
            System.err.println(parser.lineNumber);
            System.err.println(e.getMessage());
            System.exit(0);
        }
        checkDivergence(parser);
        evaluateProgram(parser);
    }

    // method to return error messages to user
    public static void printError(String error, int lineNumber) {
        System.out.println("FAIL");
        System.err.println(lineNumber);
        System.err.println(error);
        System.exit(0);
    }

    public static void evaluateProgram(Assignment parser) {
        String mainExpression = decomposeFunction(parser, "MAIN", "");
        // returns a stack of operations in a postfix order
        Queue<String> exp = infixToPostfix(mainExpression);
        int result = evaluatePostfix(exp);
        System.out.println(result);

    }

    // method to check for infinite loops/recursion by examining function bodies
    public static void checkDivergence(Assignment parser) {
        if (parser.divergence) {System.out.println("DIVERGENCE"); System.exit(0);}
    }

    // Check if the character is numeric
    public static boolean isNumeric(String str) {
        try {
            Double.parseDouble(str);
            return true;
      } catch(NumberFormatException e){
            return false;
      }
    }

    // Check if the character is an operator (* or +)
    public static boolean isOperator(String str) {
        if (str.equals("+") | str.equals("*")) {
            return true;
        }
        return false;
    }

    // Check if the character is the start of a function call (uppercase char)
    public static boolean isFunction(String str) {
        if (Character.isUpperCase(str.charAt(0))) {
            return true;
        }
        return false;
    }

    // Check if the character is a parameter (lowercase char)
    public static boolean isParameter(String str) {
        if (Character.isLowerCase(str.charAt(0))) {
            return true;
        }
        return false;
    }

    // Finds the Function name from the String token
    public static String processFunctionName(String function) {
        String funcName = "";
        //System.out.println(function);
        for (int i = 0; i < function.length(); i++) {
            if (Character.toString(function.charAt(i)).equals("(")) {
                return funcName;
            }
            funcName += function.charAt(i);
        }
        return funcName;
    }

    // Finds the Function body from the String token
    public static String processFunctionBody(String function) {
        String body = "";
         int parenthesisCount = 0;
         for (int i = 0; i < function.length(); i++) {
             if (Character.toString(function.charAt(i)).equals("(")) {
                 parenthesisCount++;
             } else if (Character.toString(function.charAt(i)).equals(")")) {
                 parenthesisCount--;
             }

             if (parenthesisCount > 0) {
                 body += function.charAt(i);
             }
         }
         return body.substring(1, body.length());
    }

    // If there is a function call in the function body, decompose the call to the function declaration
    public static String decomposeFunction(Assignment parser, String funcName, String args) {
        ArrayList<String> functionDefinition = parser.functions.get(funcName);
        String newFunction = ""; //stores decomposition as String
        boolean decomposed = false;
        boolean callPresent = false; // tells the function there is a function call that needs to be decomposed

        for (String s : functionDefinition) {
            if (isNumeric(s)) {
                //System.out.println("Number");
                newFunction += s;
            }

            else if (isParameter(s)) {
                // replace the parameter with the function body e.g. S -> A(2) where A -> x+1 then S -> 2+1
                // first check if the parameters have a function call that needs to be decomposed
                while (true) {
                    String func = findFunction(args);
                    if (func != null) {
                        String funcCall = processFunctionName(func);
                        String funcParams = processFunctionBody(func);
                        String decomposedCall = "(" + decomposeFunction(parser, funcCall, funcParams) + ")";
                        args = args.replace(func, decomposedCall);
                    } else {break;}
                }
                newFunction += "(" + args + ")";

            }

            else if (isOperator(s)) {
                //System.out.println("Operator");
                newFunction += s;
            }

            else if (isFunction(s)) {
                //System.out.println("Function");
                String funcCall = processFunctionName(s);
                String funcParams = processFunctionBody(s);

                // need to check if the function body contains the parameter so that it can swap it for the actual value in "args"
                String funcParameter = findParameter(funcParams);
                if (funcParameter != null) {
                    funcParams = funcParams.replace(funcParameter, args);
                }
                // decompose this function call further using recursion
                String decomposedCall = decomposeFunction(parser, funcCall, funcParams);
                newFunction += "(" + decomposedCall + ")";
                callPresent = true;
            }

        }

        return newFunction;
    }

    // finds the function call in the argument body
    public static String findFunction(String str) {
        boolean processing = false;
        int startInt = 0;
        int endInt = str.length();

        for (int i = 0; i < str.length(); i++) {
            if (Character.isUpperCase(str.charAt(i))) {
                if (processing) {
                    continue;
                } else {
                    startInt = i;
                    processing = true;
                }
            } else if (Character.toString(str.charAt(i)).equals(")")) {
                if (processing) {
                    processing = false;
                    endInt = i;
                    return str.substring(startInt, endInt+1);
                }
            }
        }
        return null;
    }

    // finds the function call in the argument body
        public static String findParameter(String str) {
            boolean processing = false;
            int startInt = 0;
            int endInt = str.length();

            for (int i = 0; i < str.length(); i++) {
                if (Character.isLowerCase(str.charAt(i))) {
                    if (processing) {
                        continue;
                    } else {
                        startInt = i;
                        processing = true;
                    }
                } else {
                    if (processing) {
                        processing = false;
                        endInt = i;
                        //System.out.println("PARAMETER FOUND: " + str.substring(startInt, endInt-1));
                        return str.substring(startInt, endInt+1);
                    }
                }
            }

            if (processing) {
                endInt = str.length()-1;
                return str.substring(startInt, endInt+1);
            }
            else {return null;}
        }

    // A utility function to return precedence of a given operator
    // Higher returned value means higher precedence
    public static int Prec(char ch)
    {
        switch (ch)
        {
        case '+':
        case '-':
            return 1;

        case '*':
        case '/':
            return 2;

        case '^':
            return 3;
        }
        return -1;
    }

    // The main method that converts given infix expression
    // to postfix expression.
    public static Queue<String> infixToPostfix(String exp)
    {
        // initializing empty String for result
        String result = new String("");
        Queue<String> postfix = new LinkedList<String>();

        // initializing empty stack
        Stack<String> stack = new Stack<String>();

        for (int i = 0; i<exp.length(); ++i)
        {
            char c = exp.charAt(i);

             // If the scanned character is an operand, add it to output.
            if (Character.isLetter(c)) {
                result += c;
                postfix.add(Character.toString(c));
            }

            // If the scanned character is an operand, add it to output.
            else if (Character.isDigit(c)) {
                int startInt = i;
                int endInt = i;
                for (int j = i+1; j < exp.length(); j++) {
                    if (Character.isDigit(exp.charAt(j))) {
                        endInt = j;
                        continue;
                    } else {
                        break;
                    }
                }
                String s = exp.substring(startInt, endInt+1);
                result += s;
                postfix.add(s);
                i = endInt;
            }
            // If the scanned character is an '(', push it to the stack.
            else if (Character.toString(c).equals("(")) {
                stack.push(Character.toString(c));
            }

            //  If the scanned character is an ')', pop and output from the stack
            // until an '(' is encountered.
            else if (Character.toString(c).equals(")"))
            {
                while (!stack.isEmpty() && !stack.peek().equals("(")) {
                    String elem = stack.pop();
                    result += elem;
                    postfix.add(elem);
                }

                if (!stack.isEmpty() && !stack.peek().equals("(")) {
                    System.out.println("Invalid Expression");
                    System.exit(0);
                }
                else
                    stack.pop();
            }
            else // an operator is encountered
            {
                while (!stack.isEmpty() && Prec(c) <= Prec(stack.peek().charAt(0))){
                    if(stack.peek().equals("(")) {
                        System.out.println("Invalid Expression");
                        System.exit(0);
                    }
                    String elem = stack.pop();
                    result += elem;
                    postfix.add(elem);
                }
                stack.push(Character.toString(c));
            }

        }

        // pop all the operators from the stack
        while (!stack.isEmpty()){
            if(stack.peek().equals("(")) {
                System.out.println("Invalid Expression");
                System.exit(0);
            }
            String elem = stack.pop();
            result += elem;
            postfix.add(elem);
        }
        return postfix;
    }

    // Method to evaluate value of a postfix expression from a queue of tokens(operands and operators)
    public static int evaluatePostfix(Queue<String> exp) {
        //create a stack
        Stack<Integer> stack=new Stack<Integer>();

        // Scan all characters one by one
        while (!exp.isEmpty())
        {
            String s = exp.remove();

            // If the scanned character is an operand (number here),
            // push it to the stack.
            if (isNumeric(s))
            stack.push(Integer.parseInt(s));

            //  If the scanned character is an operator, pop two
            // elements from stack apply the operator
            else
            {
                int val1 = stack.pop();
                int val2 = stack.pop();

                switch(s)
                {
                    case "+":
                    stack.push(val2+val1);
                    break;

                    case "*":
                    stack.push(val2*val1);
                    break;
              }
            }
        }
        return stack.pop();
    }

  final public void Start() throws ParseException {Token p = null;
    Token f = null;
    label_1:
    while (true) {
      try {
        jj_consume_token(DEF);
      } catch (ParseException e) {
printError("Missing keyword DEF at the start of newline", lineNumber);
      }
      try {
        jj_consume_token(SPACE);
      } catch (ParseException e) {
printError("Missing single space after DEF", lineNumber);
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAIN:{
        try {
          jj_consume_token(MAIN);
        } catch (ParseException e) {
printError("Missing MAIN keyword", lineNumber);
        }
p = null;
                currentFunc = "MAIN";
                functions.put(currentFunc, new ArrayList<String>());
                callsInCurrent = new ArrayList<String>();
        try {
          jj_consume_token(SPACE);
        } catch (ParseException e) {
printError("Missing single space after MAIN keyword", lineNumber);
        }
        try {
          p = jj_consume_token(PARAMETER);
        } catch (ParseException e) {

        }
if (p != null) {
                    printError("Parameter illegal", lineNumber);
                }
        try {
          Function(null);
        } catch (ParseException e) {
printError("MAIN function body missing", lineNumber);
        }
        break;
        }
      case FUNC_NAME:{
        try {
          f = jj_consume_token(FUNC_NAME);
        } catch (ParseException e) {
printError("Function name missing after space", lineNumber);
        }
currentFunc = f.image.toString();
                functions.put(currentFunc, new ArrayList<String>());
                callsInCurrent = new ArrayList<String>();
        try {
          jj_consume_token(SPACE);
        } catch (ParseException e) {
printError("Missing single space after '" + f.image.toString() + "'", lineNumber);
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PARAMETER:{
          try {
            p = jj_consume_token(PARAMETER);
          } catch (ParseException e) {
printError("Missing parameter after space", lineNumber);
          }
          break;
          }
        case FUNC_NAME:{
          p = jj_consume_token(FUNC_NAME);
printError("Invalid parameter name '" + p.image.toString() + "'", lineNumber);
          break;
          }
        default:
          jj_la1[0] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        try {
          jj_consume_token(SPACE);
        } catch (ParseException e) {
printError("Missing space after parameter '" + p.image.toString() + "'", lineNumber);
        }
        try {
          Function(p.image.toString());
        } catch (ParseException e) {
printError("Missing function body", lineNumber);
        }
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
// adds all the function names that have been defined
            if (definedFuncs.contains(currentFunc)) {
                printError(currentFunc + " is defined more than once", lineNumber);
            }
            definedFuncs.add(currentFunc);
      try {
        jj_consume_token(SPACE);
      } catch (ParseException e) {
printError("Missing single space after '}'", lineNumber);
      }
      try {
        jj_consume_token(SEMICOLON);
      } catch (ParseException e) {
printError("Missing ';' after right brace", lineNumber);
      }
      try {
        jj_consume_token(EOL);
      } catch (ParseException e) {
printError("Missing EOL after ';'", lineNumber-1);
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DEF:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_1;
      }
    }
    try {
      jj_consume_token(0);
    } catch (ParseException e) {
printError("Missing EOF after last function declaration", lineNumber);
    }
if (!definedFuncs.contains("MAIN")) {
            lineNumber = 0;
            printError("MAIN is not defined in the program", lineNumber);
        }

        for (HashMap.Entry<String, Integer> entry : calledFuncs.entrySet()) {
            String key = entry.getKey();
            Integer value = entry.getValue();
            if (!definedFuncs.contains(key)) {
                printError(key + " is not defined in the program", value);
            }
        }

        System.out.println("PASS");
}

// defines the MAIN function in PLM
  final public void Function(String p) throws ParseException {
    try {
      jj_consume_token(LBRACE);
    } catch (ParseException e) {
printError("Missing '{' after space", lineNumber);
    }
    try {
      jj_consume_token(SPACE);
    } catch (ParseException e) {
printError("Missing single space after '{'", lineNumber);
    }
    try {
      Body(p);
    } catch (ParseException e) {
printError("MAIN method undefined", lineNumber);
    }
    try {
      jj_consume_token(SPACE);
    } catch (ParseException e) {
printError("Missing single space after MAIN body expression", lineNumber);
    }
    try {
      jj_consume_token(RBRACE);
    } catch (ParseException e) {
printError("Missing '}' after space", lineNumber);
    }
lineNumber++;
}

// defines the function body in PLM
  final public void Body(String p) throws ParseException {Token t1 = null;
    Token t2 = null;
    String call = "";
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PARAMETER:{
        t1 = jj_consume_token(PARAMETER);
        break;
        }
      case NUMBER:{
        t1 = jj_consume_token(NUMBER);
        break;
        }
      case FUNC_NAME:{
        call = Function_Call(p);
        break;
        }
      case MAIN:{
        t1 = jj_consume_token(MAIN);
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
printError("Expecting a parameter, positive integer, or function call in body", lineNumber);
    }
if (t1 != null && t1.kind == MAIN) {
            printError("MAIN function cannot be called", lineNumber);
        }
        if (p != null && t1 != null && t1.kind == PARAMETER && !t1.image.toString().equals(p)) {
            printError("Illegal parameter in body", lineNumber);
        }
        if (p == null && t1 != null && t1.kind == PARAMETER) {
            printError("MAIN cannot contain parameters in body", lineNumber);
        }
        // adds the correct token to the function hashmap
        if (t1 == null) {
            functions.get(currentFunc).add(call);
        } else {
            functions.get(currentFunc).add(t1.image.toString());
        }

        t1 = null;
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case TIMES:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_2;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        try {
          jj_consume_token(PLUS);
        } catch (ParseException e) {
printError("Missing '+' operator in expression", lineNumber);
        }
functions.get(currentFunc).add("+");
        try {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case PARAMETER:{
            t2 = jj_consume_token(PARAMETER);
            break;
            }
          case NUMBER:{
            t2 = jj_consume_token(NUMBER);
            break;
            }
          case FUNC_NAME:{
            call = Function_Call(p);
            break;
            }
          case MAIN:{
            t2 = jj_consume_token(MAIN);
            break;
            }
          default:
            jj_la1[5] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        } catch (ParseException e) {
printError("Expecting a parameter, positive integer, or function call in body", lineNumber);
        }
        break;
        }
      case TIMES:{
        try {
          jj_consume_token(TIMES);
        } catch (ParseException e) {
printError("Missing '*' operator in expression", lineNumber);
        }
functions.get(currentFunc).add("*");
        try {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case PARAMETER:{
            t2 = jj_consume_token(PARAMETER);
            break;
            }
          case NUMBER:{
            t2 = jj_consume_token(NUMBER);
            break;
            }
          case FUNC_NAME:{
            call = Function_Call(p);
            break;
            }
          case MAIN:{
            t2 = jj_consume_token(MAIN);
            break;
            }
          default:
            jj_la1[6] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        } catch (ParseException e) {
printError("Expecting a parameter, positive integer, or function call in body", lineNumber);
        }
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
if (t2 != null && t2.kind == MAIN) {
                printError("MAIN function cannot be called", lineNumber);
            }
            // Checks if the parameter is the correct value defined at the start of the function declaration
            if (p != null && t2 != null && t2.kind == PARAMETER && !t2.image.toString().equals(p)) {
                printError("Illegal parameter in body", lineNumber);
            }
            // Checks if there are parameters when the parser examines the MAIN function
            if (p == null && t2 != null && t2.kind == PARAMETER) {
                printError("MAIN cannot contain parameters in body", lineNumber);
            }
            // adds the correct token to the functions hashmap
            if (t2 == null) {
                functions.get(currentFunc).add(call);
            } else {
                functions.get(currentFunc).add(t2.image.toString());
            }

            t2 = null;
    }
}

// defines a function call in PLM
  final public String Function_Call(String p) throws ParseException {String body = "";
    Token f = null;
    try {
      f = jj_consume_token(FUNC_NAME);
    } catch (ParseException e) {
printError("Missing function name in function call", lineNumber);
    }
    try {
      jj_consume_token(LEFT_PARENTHESIS);
    } catch (ParseException e) {
printError("Missing '(' after function call '" + f.image.toString() + "'", lineNumber);
    }
    try {
      body = Call_Body(p);
    } catch (ParseException e) {
printError("Function call '" + f.image.toString() + "' has an empty body", lineNumber);
    }
    try {
      jj_consume_token(RIGHT_PARENTHESIS);
    } catch (ParseException e) {
printError("Missing ')' after function body", lineNumber);
    }
String name = f.image.toString();
        // checks for divergence by seeing if there is RECURSION, or if:
        // the called function has been called before in the program, AND the current function has been called, and this repeated call is not in the current function body
        if (name.equals(currentFunc) || (calledFuncs.containsKey(name) && calledFuncs.containsKey(currentFunc) && !callsInCurrent.contains(name))) {
            divergence = true;
        }
        calledFuncs.put(name, lineNumber);
        callsInCurrent.add(name);
        body  = name + "(" + body + ")";
        {if ("" != null) return body;}
    throw new Error("Missing return statement in function");
}

// non-terminal used to help store the call token as one string in the hashmap
  final public String Call_Body(String p) throws ParseException {Token t1 = null;
    Token t2 = null;
    String body = "";
    String call = "";
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FUNC_NAME:
      case PARAMETER:
      case NUMBER:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PARAMETER:{
          t1 = jj_consume_token(PARAMETER);
          break;
          }
        case NUMBER:{
          t1 = jj_consume_token(NUMBER);
          break;
          }
        case FUNC_NAME:{
          call = Function_Call(p);
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      case MAIN:{
        t1 = jj_consume_token(MAIN);
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
printError("Expecting a parameter, positive integer, or function call in body", lineNumber);
    }
if (t1 != null && t1.kind == MAIN) {
            printError("MAIN function cannot be called", lineNumber);
        }
        // checks if the parameter is valid
        if (p != null && t1 != null && t1.kind == PARAMETER && !t1.image.toString().equals(p)) {
            printError("Illegal parameter in body", lineNumber);
        }
        //checks if a parameter is present when the function is MAIN
        if (p == null && t1 != null && t1.kind == PARAMETER) {
            printError("MAIN cannot contain parameters in body", lineNumber);
        }

        if (t1 != null) {
            body += t1.image.toString();
        } else {
            body += call;
        }

        t1 = null;
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case TIMES:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:{
        try {
          jj_consume_token(PLUS);
        } catch (ParseException e) {
printError("Missing '+' operator in expression", lineNumber);
        }
body += "+";
        try {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case PARAMETER:{
            t2 = jj_consume_token(PARAMETER);
            break;
            }
          case NUMBER:{
            t2 = jj_consume_token(NUMBER);
            break;
            }
          case FUNC_NAME:{
            call = Function_Call(p);
            break;
            }
          case MAIN:{
            t2 = jj_consume_token(MAIN);
            break;
            }
          default:
            jj_la1[11] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        } catch (ParseException e) {
printError("Expecting a parameter, positive integer, or function call in body", lineNumber);
        }
        break;
        }
      case TIMES:{
        try {
          jj_consume_token(TIMES);
        } catch (ParseException e) {
printError("Missing operator '*' from expression", lineNumber);
        }
body += "*";
        try {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case PARAMETER:{
            t2 = jj_consume_token(PARAMETER);
            break;
            }
          case NUMBER:{
            t2 = jj_consume_token(NUMBER);
            break;
            }
          case FUNC_NAME:{
            call = Function_Call(p);
            break;
            }
          case MAIN:{
            t2 = jj_consume_token(MAIN);
            break;
            }
          default:
            jj_la1[12] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        } catch (ParseException e) {
printError("Expecting a parameter, positive integer, or function call in body", lineNumber);
        }
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
if (t2 != null && t2.kind == MAIN) {
                printError("MAIN function cannot be called", lineNumber);
            }

            if (p != null && t2 != null && t2.kind == PARAMETER && !t2.image.toString().equals(p)) {
                printError("Illegal parameter in body", lineNumber);
            }
            if (p == null && t2 != null && t2.kind == PARAMETER) {
                printError("MAIN cannot contain parameters in body", lineNumber);
            }

            if (t2 != null) {
                body += t2.image.toString();
            } else {
                body += call;
            }

            // sets t2 as null in case there is more than 1 expression after
            t2 = null;
    }
{if ("" != null) return body;}
    throw new Error("Missing return statement in function");
}

  /** Generated Token Manager. */
  public AssignmentTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[14];
  static private int[] jj_la1_0;
  static {
	   jj_la1_init_0();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x30,0x18,0x4,0x78,0x180,0x78,0x78,0x180,0x70,0x78,0x180,0x78,0x78,0x180,};
	}

  /** Constructor with InputStream. */
  public Assignment(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Assignment(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new AssignmentTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Assignment(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new AssignmentTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new AssignmentTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Assignment(AssignmentTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(AssignmentTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[18];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 14; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 18; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
