/* Generated By:JavaCC: Do not edit this line. AssignmentConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEF = 1;
  /** RegularExpression Id. */
  int MAIN = 2;
  /** RegularExpression Id. */
  int FUNC_NAME = 3;
  /** RegularExpression Id. */
  int PARAMETER = 4;
  /** RegularExpression Id. */
  int SPACE = 5;
  /** RegularExpression Id. */
  int LEFT_BRACE = 6;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 7;
  /** RegularExpression Id. */
  int LEFT_PARENTHESIS = 8;
  /** RegularExpression Id. */
  int RIGHT_PARENTHESIS = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;
  /** RegularExpression Id. */
  int EOL = 11;
  /** RegularExpression Id. */
  int NUMBER = 12;
  /** RegularExpression Id. */
  int PLUS = 13;
  /** RegularExpression Id. */
  int TIMES = 14;
  /** RegularExpression Id. */
  int STRING = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"DEF\"",
    "\"MAIN\"",
    "<FUNC_NAME>",
    "<PARAMETER>",
    "\" \"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "<EOL>",
    "<NUMBER>",
    "\"+\"",
    "\"*\"",
    "<STRING>",
    "\" } ;\"",
    "\" { \"",
  };

}
